spring.application.name=jpa

# 뷰 리졸버
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# JPA/Hibernate
# SQL 표시 여부
spring.jpa.show-sql=true
# SQL 정렬 여부
spring.jpa.properties.hibernate.format_sql=true
# DDL Auto
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=update
# 연결 및 실행 시에 entity 기준으로 필요한 DB Table 만들어주겠다
# create - 이전 것들 다 있으면 밀고, 새로 만들겠다 (create-drop: 끄면서 먼저 삭제)
# update - 없다면 만들어주는데 있는 거 건들지 않겠다
# *** validate - 실제 DB에서 테이블과 그 테이블을 관리해주는 객체(엔티티)가 일치하는지만 검증
# *** none - 일단 실행해서 오류나면 나는 거고...

# DataSource
# spring.datasource.url=jdbc:h2:mem:5d33a3d7-4455-4beb-a24b-27622df4e86a
spring.datasource.url=jdbc:h2:mem:jpa;DB_CLOSE_DELAY=-1
# spring.datasource.username=sa
# spring.datasource.password=

# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console